name: Deploy to DeployGate

on:
  push:
    branches:
      - 'stg-release/**'

jobs:
  deploy-to-deploygate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup JDK 17
        uses: ./.github/actions/setup-java

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle

      - name: Download dependencies
        run: ./gradlew androidDependencies

      - name: Deploy to DeployGate
        run: |
          echo $ENCODED_STORE_FILE | base64 -d > staging.keystore
          ./gradlew uploadDeployGateStaging
        env:
          ENCODED_STORE_FILE: ${{ secrets.ENCODED_STORE_FILE }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          DEPLOY_GATE_OWNER_NAME: ${{ secrets.DEPLOY_GATE_OWNER_NAME }}
          DEPLOY_GATE_API_KEY: ${{ secrets.DEPLOY_GATE_API_KEY }}
